name = "PackedStructs"
uuid = "3f4c4bcc-b4a0-426b-9836-06ea373f3441"
version = "0.3.0"
authors = ["Patrick Häcker <patrick.haecker@de.bosch.com>"]

[workspace]
projects = ["test"]

[deps]
EmulatedBitIntegers = "344cc1fc-1294-4796-b5db-6b4bd1573fb6"
ExproniconLite = "55351af7-c7e9-48d6-89ff-24e801d99491"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[weakdeps]
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"

[extensions]
PackedStructsConstructionBaseExt = "ConstructionBase"

[sources]
EmulatedBitIntegers = {rev = "main", url = "https://github.com/PatrickHaecker/EmulatedBitIntegers.jl"}

[compat]
ConstructionBase = "1.5"
EmulatedBitIntegers = "0.4"
ExproniconLite = "0.10"
PrecompileTools = "1"
julia = "1.10"
